# Generated by Django 5.0.4 on 2024-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
