# Generated by Django 5.0.4 on 2024-04-21 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_accountmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
