# Generated by Django 5.0.4 on 2024-04-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_transactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='models.usermodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='models.usermodel'),
        ),
    ]
